"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ku_as45vs5isd^px=t#m8g#^*x7f=w#gw-xb^t@^-pom)r^t6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '.kavia.ai',
    'localhost',
    '127.0.0.1',
    'testserver',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
X_FRAME_OPTIONS = 'ALLOWALL'

# MQTT configuration
# The following environment variables can be set to control MQTT behavior:
# - MQTT_HOST: Broker hostname (default: localhost)
# - MQTT_PORT: Broker port (default: 1883)
# - MQTT_USERNAME: Username for broker auth (optional)
# - MQTT_PASSWORD: Password for broker auth (optional)
# - MQTT_CLIENT_ID: Custom MQTT client ID (optional; default auto-generated)
# - MQTT_SUBSCRIBE_TOPIC: Topic to subscribe to (default: test/in)
# - MQTT_PUBLISH_TOPIC: Topic to publish to (default: test/out)
# - MQTT_QOS: QoS level for subscribe/publish (0,1,2) default: 0
# - MQTT_KEEPALIVE: Keepalive seconds (default: 60)
# - MQTT_TLS: "true" to enable TLS (default: false)
import os

MQTT_SETTINGS = {
    "HOST": os.getenv("MQTT_HOST", "localhost"),
    "PORT": int(os.getenv("MQTT_PORT", "1883")),
    "USERNAME": os.getenv("MQTT_USERNAME", None),
    "PASSWORD": os.getenv("MQTT_PASSWORD", None),
    "CLIENT_ID": os.getenv("MQTT_CLIENT_ID", None),
    "SUBSCRIBE_TOPIC": os.getenv("MQTT_SUBSCRIBE_TOPIC", "test/in"),
    "PUBLISH_TOPIC": os.getenv("MQTT_PUBLISH_TOPIC", "test/out"),
    "QOS": max(0, min(2, int(os.getenv("MQTT_QOS", "0")))),
    "KEEPALIVE": int(os.getenv("MQTT_KEEPALIVE", "60")),
    "TLS": os.getenv("MQTT_TLS", "false").lower() in ("1", "true", "yes"),
}
